### ISSUE TITLE
Collectd.5.4.0.20140219 fails to build on Ubuntu 12.04.3 LTS

### ISSUE THREAD

**Issue by sylock** [perfwatcher/perfwatcher#45]
I wanted to try perfwatcher/collectd. I successfully compile collectd-pw on the client (the agent) but I can't make it building on Ubuntu 12.04.3 LTS.
gcc --version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Here is the error message at compile time. It says that the "name" variable (a char pointer) is unused. I tried to delete the line just to see. If I do, I have another error later saying that it uses a non-declared variable named "name" ;)

It seems to be a bug in the gcc checks. What do you think about it? How could I resolve it?

procnetstat.c: In function ‘read_statistics_from_cache’:
procnetstat.c:715:23: error: variable ‘name’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors
make[3]: **\* [procnetstat.lo] Error 1
make[3]: Leaving directory `/tmp/collectd-5.4.0.20140219/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory`/tmp/collectd-5.4.0.20140219/src'
make[1]: **\* [all] Error 2
make[1]: Leaving directory `/tmp/collectd-5.4.0.20140219/src'
make: **\* [all-recursive] Error 1
